<a href="https://colab.research.google.com/github/24cse025srutipatnaik/DMDW-Assignments/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
df=pd.read_csv('/content/data.csv')

In [7]:
df.tail()

    roll name  age gen branch sec
10    11    k   20   f    cse   b
11    12    l   21   m    cse   b
12    13    m   22   f    cse   b
13    14    n   20   m    cse   b
14    15    o   12   f    cse   b

In [6]:
df

    roll name  age gen branch sec
0      1    a   18   m    cse   b
1      2    b   19   m    cse   b
2      3    c   21   f    cse   b
3      4    d   20   f    cse   b
4      5    e   17   f    cse   b
5      6    f   18   m    cse   b
6      7    g   19   f    cse   b
7      8    h   21   m    cse   b
8      9    i   20   m    cse   b
9     10    j   19   f    cse   b
10    11    k   20   f    cse   b
11    12    l   21   m    cse   b
12    13    m   22   f    cse   b
13    14    n   20   m    cse   b
14    15    o   12   f    cse   b

In [8]:
df.head()

   roll name  age gen branch sec
0     1    a   18   m    cse   b
1     2    b   19   m    cse   b
2     3    c   21   f    cse   b
3     4    d   20   f    cse   b
4     5    e   17   f    cse   b

In [9]:
df.head(6)

   roll name  age gen branch sec
0     1    a   18   m    cse   b
1     2    b   19   m    cse   b
2     3    c   21   f    cse   b
3     4    d   20   f    cse   b
4     5    e   17   f    cse   b
5     6    f   18   m    cse   b

In [10]:
df.tail(6)

    roll name  age gen branch sec
9     10    j   19   f    cse   b
10    11    k   20   f    cse   b
11    12    l   21   m    cse   b
12    13    m   22   f    cse   b
13    14    n   20   m    cse   b
14    15    o   12   f    cse   b

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    15 non-null     int64
 1   name    15 non-null     object
 2   age     15 non-null     int64
 3   gen     15 non-null     object
 4   branch  15 non-null     object
 5   sec     15 non-null     object
dtypes: int64(2), object(4)
memory usage: 852.0+ bytes

In [12]:
df.describe()

            roll        age
count  15.000000  15.000000
mean    8.000000  19.133333
std     4.472136   2.386470
min     1.000000  12.000000
25%     4.500000  18.500000
50%     8.000000  20.000000
75%    11.500000  20.500000
max    15.000000  22.000000

In [13]:
df.shape

(15, 6)

In [14]:
df.columns

Index(['roll', 'name', 'age', 'gen', 'branch', 'sec'], dtype='object')

In [15]:
df.dtypes

roll       int64
name      object
age        int64
gen       object
branch    object
sec       object
dtype: object

In [16]:
df.isnull()

     roll   name    age    gen  branch    sec
0   False  False  False  False   False  False
1   False  False  False  False   False  False
2   False  False  False  False   False  False
3   False  False  False  False   False  False
4   False  False  False  False   False  False
5   False  False  False  False   False  False
6   False  False  False  False   False  False
7   False  False  False  False   False  False
8   False  False  False  False   False  False
9   False  False  False  False   False  False
10  False  False  False  False   False  False
11  False  False  False  False   False  False
12  False  False  False  False   False  False
13  False  False  False  False   False  False
14  False  False  False  False   False  False

In [17]:
df.isnull().sum()

roll      0
name      0
age       0
gen       0
branch    0
sec       0
dtype: int64

In [18]:
df.iloc[1]

roll        2
name        b
age        19
gen         m
branch    cse
sec         b
Name: 1, dtype: object

In [19]:
df.loc(0)

In [20]:
ages=df['age']

In [21]:
ages

0     18
1     19
2     21
3     20
4     17
5     18
6     19
7     21
8     20
9     19
10    20
11    21
12    22
13    20
14    12
Name: age, dtype: int64

In [22]:
adults=df[df['age']>20]
print("Those whose are elder than 20 years  \n", adults)

Those whose are elder than 20 years
     roll name  age gen branch sec
2      3    c   21   f    cse   b
7      8    h   21   m    cse   b
11    12    l   21   m    cse   b
12    13    m   22   f    cse   b

In [23]:
adults=df[df['age']<=20]
print("Those whose are elder than 20 years  \n", adults)

Those whose are elder than 20 years
     roll name  age gen branch sec
0      1    a   18   m    cse   b
1      2    b   19   m    cse   b
3      4    d   20   f    cse   b
4      5    e   17   f    cse   b
5      6    f   18   m    cse   b
6      7    g   19   f    cse   b
8      9    i   20   m    cse   b
9     10    j   19   f    cse   b
10    11    k   20   f    cse   b
13    14    n   20   m    cse   b
14    15    o   12   f    cse   b

In [25]:
age_filtered_students = df[(df['age'] >= 19) & (df['age'] <= 20)]
male_students_in_age_range = age_filtered_students[age_filtered_students['gen'] == 'm']
print("Male students aged 19 to 20:\n", male_students_in_age_range)

Male students aged 19 to 20:
     roll name  age gen branch sec
1      2    b   19   m    cse   b
8      9    i   20   m    cse   b
13    14    n   20   m    cse   b

In [27]:
sorted_students_by_age = df.sort_values(by='age', ascending=True)
print("All students sorted by age (lower to higher):\n", sorted_students_by_age)

All students sorted by age (lower to higher):
     roll name  age gen branch sec
14    15    o   12   f    cse   b
4      5    e   17   f    cse   b
5      6    f   18   m    cse   b
0      1    a   18   m    cse   b
6      7    g   19   f    cse   b
1      2    b   19   m    cse   b
9     10    j   19   f    cse   b
3      4    d   20   f    cse   b
13    14    n   20   m    cse   b
8      9    i   20   m    cse   b
10    11    k   20   f    cse   b
2      3    c   21   f    cse   b
7      8    h   21   m    cse   b
11    12    l   21   m    cse   b
12    13    m   22   f    cse   b