<a href="https://colab.research.google.com/github/24cse025srutipatnaik/DMDW-Assignments/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/data.csv')

In [ ]:
df.tail()

    roll name   age gen branch sec
10  10.0    i  21.0   m    cse   b
11  12.0    j  22.0   m    cse   b
12  13.0    k  21.0   f    cse   b
13  14.0    l  20.0   m    cse   b
14  15.0    m  19.0   f    cse   b

In [ ]:
df

    roll name   age  gen branch  sec
0    NaN  NaN   NaN  NaN    NaN  NaN
1    1.0    a  19.0    m    cse    b
2    2.0    b  23.0    f    cse    b
3    3.0    c  21.0    f    cse    b
4    4.0    d  20.0    m    cse    b
5    5.0    e  18.0    m    cse    b
6    6.0  NaN  17.0    f    cse    b
7    7.0    f  20.0    f    cse    b
8    8.0    g  22.0    f    cse    b
9    9.0    h  18.0    m    cse    b
10  10.0    i  21.0    m    cse    b
11  12.0    j  22.0    m    cse    b
12  13.0    k  21.0    f    cse    b
13  14.0    l  20.0    m    cse    b
14  15.0    m  19.0    f    cse    b

In [ ]:
df.head()

   roll name   age  gen branch  sec
0   NaN  NaN   NaN  NaN    NaN  NaN
1   1.0    a  19.0    m    cse    b
2   2.0    b  23.0    f    cse    b
3   3.0    c  21.0    f    cse    b
4   4.0    d  20.0    m    cse    b

In [ ]:
df.head(6)

   roll name   age  gen branch  sec
0   NaN  NaN   NaN  NaN    NaN  NaN
1   1.0    a  19.0    m    cse    b
2   2.0    b  23.0    f    cse    b
3   3.0    c  21.0    f    cse    b
4   4.0    d  20.0    m    cse    b
5   5.0    e  18.0    m    cse    b

In [ ]:
df.tail(6)

    roll name   age gen branch sec
9    9.0    h  18.0   m    cse   b
10  10.0    i  21.0   m    cse   b
11  12.0    j  22.0   m    cse   b
12  13.0    k  21.0   f    cse   b
13  14.0    l  20.0   m    cse   b
14  15.0    m  19.0   f    cse   b

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    14 non-null     float64
 1   name    13 non-null     object
 2   age     14 non-null     float64
 3   gen     14 non-null     object
 4   branch  14 non-null     object
 5   sec     14 non-null     object
dtypes: float64(2), object(4)
memory usage: 852.0+ bytes

In [ ]:
df.describe()

            roll        age
count  14.000000  14.000000
mean    7.785714  20.071429
std     4.560340   1.730464
min     1.000000  17.000000
25%     4.250000  19.000000
50%     7.500000  20.000000
75%    11.500000  21.000000
max    15.000000  23.000000

In [ ]:
df.shape

(15, 6)

In [ ]:
df.columns

Index(['roll', 'name', 'age', 'gen', 'branch', 'sec'], dtype='object')

In [ ]:
df.dtypes

roll      float64
name       object
age       float64
gen        object
branch     object
sec        object
dtype: object

In [ ]:
df.isnull()

     roll   name    age    gen  branch    sec
0    True   True   True   True    True   True
1   False  False  False  False   False  False
2   False  False  False  False   False  False
3   False  False  False  False   False  False
4   False  False  False  False   False  False
5   False  False  False  False   False  False
6   False   True  False  False   False  False
7   False  False  False  False   False  False
8   False  False  False  False   False  False
9   False  False  False  False   False  False
10  False  False  False  False   False  False
11  False  False  False  False   False  False
12  False  False  False  False   False  False
13  False  False  False  False   False  False
14  False  False  False  False   False  False

In [ ]:
df.isnull().sum()

roll      1
name      2
age       1
gen       1
branch    1
sec       1
dtype: int64

In [ ]:
df.iloc[1]

roll       1.0
name         a
age       19.0
gen          m
branch     cse
sec          b
Name: 1, dtype: object

In [ ]:
df.loc(0)

In [ ]:
ages=df['age']

In [ ]:
ages

0      NaN
1     19.0
2     23.0
3     21.0
4     20.0
5     18.0
6     17.0
7     20.0
8     22.0
9     18.0
10    21.0
11    22.0
12    21.0
13    20.0
14    19.0
Name: age, dtype: float64

In [ ]:
adults=df[df['age']>20]
print("Those whose are elder than 20 years  \n", adults)

Those whose are elder than 20 years
     roll name   age gen branch sec
2    2.0    b  23.0   f    cse   b
3    3.0    c  21.0   f    cse   b
8    8.0    g  22.0   f    cse   b
10  10.0    i  21.0   m    cse   b
11  12.0    j  22.0   m    cse   b
12  13.0    k  21.0   f    cse   b

In [ ]:
adults=df[df['age']<=20]
print("Those whose are elder than 20 years  \n", adults)

Those whose are elder than 20 years
     roll name   age gen branch sec
1    1.0    a  19.0   m    cse   b
4    4.0    d  20.0   m    cse   b
5    5.0    e  18.0   m    cse   b
6    6.0  NaN  17.0   f    cse   b
7    7.0    f  20.0   f    cse   b
9    9.0    h  18.0   m    cse   b
13  14.0    l  20.0   m    cse   b
14  15.0    m  19.0   f    cse   b

In [ ]:
Age_and_gender_filtered=df[df['age']>=19 & df['age']<20  &  df['gen']=='m']
print("Between 19 and 20 age male:  \n", Age_and_gender_filtered)

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]